name: asptraffic
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3=1.29.1
  - botocore=1.32.1
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.16.0
  - cryptography=41.0.7
  - idna=3.4
  - jmespath=1.0.1
  - libcxx=14.0.6
  - libffi=3.4.2
  - libsqlite=3.41.2
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.12
  - pip=23.1.2
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - readline=8.2
  - s3transfer=0.7.0
  - setuptools=67.7.2
  - six=1.16.0
  - tk=8.6.12
  - urllib3=1.26.18
  - wheel=0.40.0
  - xz=5.2.6
  - pip:
      - sumolib==1.17.0
      - traci==1.17.0
